### PR TITLE
0.1.2

### PR DESCRIPTION
**Pull request by nhanitvn**

### CODE REVIEW

**Comment by ctn** [comment]
Mapping `train_model` to `train_base_model` is incorrect in principle.

A `modeler` definitively needs to `train_model`. How it does that in a matter of implementation. So, if you need to `train_base_model` in that process, then that method should be *added*.

Further, the concept of `base_model` is specific to models that wrap some base model, and not to all models.

Therefore, anything referring to a `base_model` should be implemented in its own base class, e.g., `WrappedModel`, and inherited accordingly.

Please redesign. If it is important for you to make the Feb 1 milestone, let’s consider moving this train along, but into its own branch, rather than merging into `main`.

**Comment by nhanitvn** [comment]
I see. Let me clarify the following points:
- The `base_model` here refers to the **native models** such as `sklearn`, `keras` ones that back the corresponding h1st MLModel. Previously, the `train_model`'s name was `train` and it was used to train the native models. It must be implemented by the user because that is not the framework's responsibility. cc @TgithubJ
- We now have `train_model` and `build_model`. If `train_model` is for training the corresponding h1st MLModel then we have a redundancy here.
That's why I renamed `train_model` to `train_base_model` to make the meaning clear. Maybe it should be `train_native_model` instead :D.

**Comment by ctn** [comment]
@nhanitvn you may be assuming incorrectly that I didn’t understand what you were doing. I believe I did.

On the other hand, I am not sure you understood my key architectural comments. We can discuss live.

**Comment by ctn** [comment]
For example, do you agree that at the base `Model` level, there *should not* be any references to any concept of `base` or `native` models? That may help us get on the same page first.

**Comment by nhanitvn** [comment]
Agree Christopher. Let me close this PR.

**Comment by ctn** [comment]
👍 please do follow up with support for base-model handling.

**Pull request closed without merging**
