### PR TITLE
(WIP) doc: update documentation structure

### PR DESCRIPTION
**Pull request by khoama**
This PR updates documentation for h1st.ai

### CODE REVIEW

**Comment by ctn** [comment]
Ooops. There is also a `docs` branch with work going on there.

**Comment by ctn** [comment]
@khoama would you put these ideas into [`docs` ](https://github.com/h1st-ai/h1st/tree/docs) and work on that branch instead? Let me know if https://github.com/h1st-ai/h1st/blob/docs/docs/README.rst is sufficient how-to. If not please update those instructions as well.

**Comment by ctn** [comment]
I have also shared out access to https://readthedocs.org/dashboard/

**Comment by khoama** [comment]
sure @ctn

**Comment by ctn** [comment]
Any updates on this PR?

**Pull request closed without merging**
