### PR TITLE
Remove `__init__.py` as they are no longer necessary.

### PR DESCRIPTION
**Pull request by ctn**
See https://github.com/h1st-ai/h1st/issues/111

### CODE REVIEW

**Comment by ctn** [comment]
cc @TheVinhLuong102 @phanhongan

**Comment by nhanitvn** [comment]
I think we just need to delete empty `__init__.py` files which are needed by Python 2. The `__init__.py` files are also used to expose sub-modules, classes to avoid long/awkward import statements, for example `from h1st.model.repository import ModelRepository` instead of `from h1st.model.repository.model_repository import ModelRepository` and common/initialization code/documentation for that sub-module. So we should only delete `__init__.py` files with unnecessary code/documentation.

**Comment by ctn** [comment]
I think for ease of management and consistency, let’s *require* only one
consistent way of referencing modules and that is through the full path.
Allowing shortcuts would invite sloppiness.

—
Algorithms of the Mind
Christopher Nguyen
Co-Founder & CEO
A I T O M A T I C, Inc.
linkedin.com/in/ctnguyen

**Comment by nhanitvn** [comment]
OK. Then could you help update the import statement in `h1st/core/context.py` too. Currently it is `from h1st.model.repository import ModelRepository`.

**Comment by ctn** [comment]
👍

—
Algorithms of the Mind
Christopher Nguyen
Co-Founder & CEO
A I T O M A T I C, Inc.
linkedin.com/in/ctnguyen

**Comment by ctn** [comment]
"All checks have passed."  😎

Please merge and close out https://github.com/h1st-ai/h1st/issues/111 @nhanitvn @Shiti cc @TheVinhLuong102

**Review by nhanitvn — APPROVED** [review]

**Pull request merged**
