### PR TITLE
Update organization of Docs

### PR DESCRIPTION
**Pull request by ctn**
.. incorporating @trile’s contributions.

### CODE REVIEW

**Comment by ctn** [comment]
As always, view the latest compiled docs at https://h1st.readthedocs.io/en/latest/README.html

**Comment by khoama** [comment]
docs branch updated instead

**Comment by ctn** [comment]
You closed the wrong one 😉

I think you mean to close #118?

**Comment by ctn** [comment]
@khoama pls review & merge.

**Review by khoama — APPROVED** [review]
lgtm

**Pull request merged**
