### PR TITLE
Update concepts and tutorials

### PR DESCRIPTION
**Pull request by trile**
- Update Knowledge-First page to separated Knowledge-First and Oracle, add EIE diagram.
- Update Quick-start section (remove the old Model section and prepare for new Modeler and Model, add Oracle section).
- Add Nhan's Modeler and Model tutorial with Iris data under Examples, create placeholder file for TJ's Oracle IoT tutorial.

### CODE REVIEW

**Comment by trile** [comment]
Generated docs: https://h1st--126.org.readthedocs.build/en/126/

**Comment by trile** [comment]
@ctn I accidentally click on build stable in readthedocs while trying to find the specific build for this PR. It showed the stable build failed, I hope I did not create some troubles.

**Comment by ctn** [comment]
No worries I'll take a look

**Comment by ctn** [comment]
lgtm

**Review by ctn — APPROVED** [review]
Approved.

**Pull request merged**
